services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./blog.db
        target: /app/blog.db
      - ${SSL_CERT_PATH}:/ssl/cert.pem
      - ${SSL_KEY_PATH}:/ssl/key.pem
    environment:
      - ENV=production
      - SSL_CERT_PATH=/ssl/cert.pem
      - SSL_KEY_PATH=/ssl/key.pem
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
