version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./blog.db:/app/blog.db
      - ${SSL_CERT_PATH}:/ssl/cert.pem
      - ${SSL_KEY_PATH}:/ssl/key.pem
      - ./.env:/app/.env
    environment:
      - ENV=production
      - SSL_CERT_PATH=/ssl/cert.pem
      - SSL_KEY_PATH=/ssl/key.pem
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
