networks:
  web:
    external: true

services:
  web:
    image: tylergilman/tylergilman:prod
    user: "1001:1001"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=prod"
      - "traefik.http.routers.tyler.rule=Host(`tylergilman.com`)"
      - "traefik.http.routers.tyler.entrypoints=websecure"
      - "traefik.http.routers.tyler.tls.certresolver=leresolver"
      - "traefik.http.services.tyler.loadbalancer.server.port=8080"
      - "traefik.http.routers.tyler.middlewares=security-headers@file"
    volumes:
      - ./blog.db:/app/blog.db
      - ./.env:/app/.env:ro
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 10s
      retries: 3
