networks:
  web:
    external: true  # Use existing Traefik network

services:
  web:
    image: tylergilman/tylergilman:prod
    user: "1001:1001"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=prod"
      - "traefik.http.routers.tyler.rule=Host(`tylergilman.com`)"
      - "traefik.http.routers.tyler.entrypoints=websecure"
      - "traefik.http.routers.tyler.tls.certresolver=leresolver"
      - "traefik.http.services.tyler.loadbalancer.server.port=8080"
    volumes:
      - ./blog.db:/app/blog.db
      - ./.env:/app/.env:ro
    environment:
      - ENV=production
    restart: unless-stopped
