version: '3'

volumes:
  db-data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tylergilman_dev
    ports:
      - "8002:8080"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - ENV=development
      - DEV_PORT=8080
      - DB_PATH=/app/data/blog.db
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped