version: '3.8'

networks:
  web:
    external: false

services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--ping=true"  # Enable ping for health checks
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    deploy:
      replicas: 3  # Default number of replicas
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`tylergilman.com`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      # Add load balancing configuration
      - "traefik.http.services.web.loadbalancer.passhostheader=true"
    volumes:
      - type: bind
        source: ./blog.db
        target: /app/blog.db
      - ./.env:/app/.env
    environment:
      - ENV=production
      - DEV_PORT=8080
    restart: unless-stopped
