version: '3.8'

services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80" #http
      - "8080:8080" # web ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    labels:
      - "traefik.http.routers.web.rule=Host(`tylergilman.com`)"
    volumes:
      - type: bind
        source: ./blog.db
        target: /app/blog.db
      - ./.env:/app/.env
    environment:
      - ENV=production
      - DEV_PORT=8080
    restart: unless-stopped
