// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/TylerGilman/nereus_main_site/views/components"
)

func Base(page_mode string, isAdmin bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><title>Nereus Tech</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link type=\"text/css\" rel=\"stylesheet\" href=\"/public/styles/base.css\"><link type=\"text/css\" rel=\"stylesheet\" href=\"/public/styles/blog.css\"><link type=\"text/css\" rel=\"stylesheet\" href=\"/public/styles/home.css\"><link type=\"text/css\" rel=\"stylesheet\" href=\"/public/styles/projects.css\"><script src=\"/public/js/fishtank.js\" defer></script><script src=\"/public/js/navigation.js\" defer></script><script src=\"https://unpkg.com/htmx.org@1.9.9\" defer></script><script src=\"https://cdn.jsdelivr.net/npm/marked/marked.min.js\"></script><script src=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js\"></script><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css\"></head><body class=\"antialiased\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navigation(page_mode, isAdmin).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"modal-container\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script type=\"text/javascript\">\n\ndocument.addEventListener('htmx:afterSettle', function(event) {\n    if (window.initializeNavBar) {\n        window.initializeNavBar();\n    }\n});\n\n    document.body.addEventListener('htmx:afterSwap', function(event) {\n        if (event.detail.target.id === 'modal-container') {\n            requestAnimationFrame(() => {\n                const overlay = document.getElementById('modal-overlay');\n                if (overlay) {\n                    overlay.classList.add('show');\n                }\n            });\n        }\n    });\n    document.body.addEventListener('htmx:afterOnLoad', function(event) {\n        if (event.detail.elt.id === 'modal-container') {\n            document.body.classList.add('modal-open');\n            setTimeout(function() {\n                const overlay = document.getElementById('modal-overlay');\n                if (overlay) {\n                    overlay.classList.add('show');\n                }\n            }, 50);\n        }\n    });\n\n    document.body.addEventListener('htmx:beforeOnLoad', function(event) {\n        if (event.detail.requestConfig.target === '#modal-container') {\n            const overlay = document.getElementById('modal-overlay');\n            if (overlay) {\n                overlay.classList.remove('show');\n                setTimeout(function() {\n                    document.body.classList.remove('modal-open');\n                }, 300);\n            }\n        }\n    });\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
