// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package blog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/TylerGilman/nereus_main_site/views/layouts"
)

func AdminBlogPost(adminPass string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto px-4 py-8\"><h1 class=\"text-2xl font-bold mb-4\">Create New Blog Post</h1><form hx-post=\"/admin/blog/create\" hx-target=\"#message\" class=\"space-y-4\"><input type=\"hidden\" name=\"admin_pass\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(adminPass)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/blog/admin.templ`, Line: 12, Col: 71}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div><label for=\"title\" class=\"block mb-1\">Title</label> <input type=\"text\" id=\"title\" name=\"title\" required class=\"w-full p-2 border rounded\"></div><div><label for=\"author\" class=\"block mb-1\">Author</label> <input type=\"text\" id=\"author\" name=\"author\" required class=\"w-full p-2 border rounded\"></div><div><label for=\"category\" class=\"block mb-1\">Category</label> <select id=\"category\" name=\"category\" required class=\"w-full p-2 border rounded\"><option value=\"Life\">Life</option> <option value=\"Technology\">Technology</option> <option value=\"Philosophy\">Philosophy</option> <option value=\"Random\">Random</option></select></div><div><label for=\"summary\" class=\"block mb-1\">Summary</label> <textarea id=\"summary\" name=\"summary\" required class=\"w-full p-2 border rounded\" rows=\"3\"></textarea></div><div><label for=\"content\" class=\"block mb-1\">Content</label> <textarea id=\"content\" name=\"content\" required class=\"w-full p-2 border rounded\" rows=\"10\"></textarea></div><div><label for=\"imageUrl\" class=\"block mb-1\">Image URL</label> <input type=\"url\" id=\"imageUrl\" name=\"imageUrl\" class=\"w-full p-2 border rounded\"></div><div><button type=\"submit\" class=\"bg-red-400 text-white p-2 rounded hover:bg-red-500\">Create Post</button></div></form><div id=\"message\" class=\"mt-4\"></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base("Admin - New Blog Post").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
